### ISSUE TITLE
multi-buildpacks

### ISSUE THREAD

**Issue by lazydino** [deis/slugbuilder#51]
Does deis workflow slugbuilder support multi-buildpacks? I want to try a special build pack at https://github.com/lastko/heroku-buildpack-edgejs Would I be able to configure primary and secondary build packs as it mentioned there?

**Comment by bacongobbler** [comment]
yes. use the multi-buildpack buildpack. See https://github.com/ddollar/heroku-buildpack-multi

**Comment by mboersma** [comment]
Slugbuilder specifically contains Heroku's multi-buildpack at https://github.com/heroku/heroku-buildpack-multi, a fork of ddollar's. I retested this recently with https://github.com/dzuelke/heroku-multipack-nodejs-php-example, so you could also check that repository for a working example.

**Comment by lazydino** [comment]
Hi,

I wasn't able to set BUILDPACK_URL with ddollar's fork, or any other build pack

root@UBC809:~/edgetest# deis config:set BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git
Creating config... Error:
404 Not Found
detail: Not found.

root@UBC809:~/edgetest# deis config:set BUILDPACK_URL=https://github.com/dpiddy/heroku-buildpack-ruby-minimal
Creating config... Error:
404 Not Found
detail: Not found.

What goes wrong? I am running deis against GKE..

Since deis does not support buidlpacks:set and buildpacks:add ,  would I be fine just create a .buildpacks at the root of my repos like

https://github.com/lastko/heroku-buildpack-edgejs.git
https://github.com/sibeliusseraphini/heroku-buildpack-nodejs-bower-grunt

as the heroku-buildpack-nodejs-bower-grunt as my 'primary buildpack'?

**Comment by bacongobbler** [comment]
@lazydino that 404 error means the application you are pointing to is incorrect. You're likely in the wrong directory. Try running the same command with `-a` to explicitly call out the application name you wish to set.

> Since deis does not support buidlpacks:set and buildpacks:add

`heroku buildpacks:set` is the same as `heroku config:set BUILDPACK_URL=...`. It's just an alias, similar to how `deis pull` is an alias for `deis builds:create`. :)

> would I be fine just create a .buildpacks at the root of my repos like
> 
> https://github.com/lastko/heroku-buildpack-edgejs.git
> https://github.com/sibeliusseraphini/heroku-buildpack-nodejs-bower-grunt
> 
> as the heroku-buildpack-nodejs-bower-grunt as my 'primary buildpack'?

Since we already have heroku-buildpack-multi built into slugbuilder, yes it should be fine to create a .buildpacks file, commit it to the repository and push. You'll probably want heroku-buildpack-nodejs-bower-grunt as the first one on the list if it's your primary buildpack, though.
