### ISSUE TITLE
s3aws: Path not found: home/example-go:git-779ca3d7/push/slug.tgz

### ISSUE THREAD

**Issue by rimusz** [deis/slugbuilder#68]
Tried to build deis/example-go in beta3 and got this in the logs

```
INFO [example-go]: rimas created initial release
INFO [example-go]: domain example-go added
INFO [example-go]: rimas deployed 779ca3d
INFO [example-go]: Cleaning up RCS for releases older than v2 (latest)
INFO [example-go]: Cleaning up orphaned environment var secrets
example-go-v2-web-uhm89 -- 2016/04/29 12:39:59 Error downloading home/example-go:git-779ca3d7/push/slug.tgz (s3aws: Path not found: home/example-go:git-779ca3d7/push/slug.tgz)
example-go-v2-web-uhm89 -- 2016/04/29 12:40:21 Error downloading home/example-go:git-779ca3d7/push/slug.tgz (s3aws: Path not found: home/example-go:git-779ca3d7/push/slug.tgz)
example-go-v2-web-uhm89 -- 2016/04/29 12:40:02 Error downloading home/example-go:git-779ca3d7/push/slug.tgz (s3aws: Path not found: home/example-go:git-779ca3d7/push/slug.tgz)
```

Used Minio as the object storage

**Comment by kmala** [comment]
did minio restart in the mean time?

**Comment by ozanyurt** [comment]
did you solve this?
I can successfully deploy with redeploy and delete minio pod.

**Comment by Joshua-Anderson** [comment]
This was almost certainly caused by a minio restart and then kubernetes trying to redeploy the app. Since the slug no longer exists, it can no longer be deployed. What's odd is that the control plane is still running and recognizes the app. I guess the database hasn't restarted yet?

Either way, I think that lack of data persistence is expected of minio and this can safely be closed.
